# Generated by Django 5.2.1 on 2025-05-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('processed_file', models.FileField(upload_to='processed_files/', verbose_name='处理后的文件')),
                ('processing_params', models.JSONField(blank=True, null=True, verbose_name='处理参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Excel处理记录',
                'verbose_name_plural': 'Excel处理记录',
            },
        ),
    ]
