# Generated by Django 5.2.1 on 2025-05-22 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidapp', '0002_excelprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerBidInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('bidder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='中标单位名称')),
                ('area_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='地区代码')),
                ('win_amt', models.FloatField(blank=True, null=True, verbose_name='中标金额')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('tender_org_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='招标单位')),
                ('tos', models.CharField(blank=True, max_length=50, null=True, verbose_name='类别')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='详情页URL')),
                ('notice_content', models.TextField(blank=True, null=True, verbose_name='公告内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='corp_code', on_delete=django.db.models.deletion.CASCADE, to='bidapp.companyinfo', to_field='corp_code', verbose_name='公司')),
            ],
            options={
                'verbose_name': '中标信息',
                'verbose_name_plural': '中标信息',
                'db_table': 'winner_bid_info',
                'unique_together': {('company', 'project_name')},
            },
        ),
    ]
