name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: tbbid
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            cd /home/tbbid/backend
            pwd
            git pull
            source .venv/bin/activate
            uv pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
            # 6. 运行数据库迁移
            python3 manage.py migrate
            # 7. 重启后端服务（使用 supervisor）
            sudo supervisorctl restart backend
